version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: api-lab-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
